Prune
backube/scribe pull request #150
Opened 2021-04-04 14:33 UTC by husky-parul

**Describe what this PR does**
Adds `FORGET_OPTIONS` and `prune` functionalities for restic based backups.

**Is there anything that requires special attention?**
NA

**Related issues:**
#89

2021-04-05 14:11 UTC, JohnStrunk requested changes

2021-04-05 14:11 UTC, JohnStrunk commented on controllers/replicationsource_controller.go
> +		l.V(1).Info("e.g. --keep-hourly 2 --keep-daily 1", "forgetOptions", forgetOptions)
```suggestion
		l.V(1).Info("restic forget options", "options", forgetOptions)
```

2021-04-06 16:32 UTC, husky-parul commented on controllers/restic_common.go
> +	foWithin := "--keep-within 3w15h"
Should we make the fields of `ResticRetainPolicy` `optional` then?

2021-04-06 16:50 UTC, JohnStrunk commented on controllers/restic_common.go
> +	foWithin := "--keep-within 3w15h"
Yes, they should all be optional. If none are specified, we can default to keep just the latest backup (`--keep-last 1`), but if any are specified, we should just use what's provided.

2021-04-07 17:32 UTC, merged